version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      ConnectionStrings__DefaultConnection: "Host=92.63.176.224;Database=travel;Username=postgres;Password=root"
    ports:
      - "5000:8080"
    restart: always
